### PR TITLE
Enable scrolling in modal dialogs

### PR DESCRIPTION
**Pull request by andrewmoise**
Hey, this is a cool project + I like it -- I have a couple of PRs to send for minor issues I've encountered though.

For this one, the setup doesn't work well on my machine because the modal dialogs on setup are too big to fit in the browser window sometimes. This patch enables scrolling of the content on modal dialogs when needed to make sure the user can find all the stuff.

### CODE REVIEW

**Comment by benpate** [comment]
Sure.  This looks good.  Thank you!

And please let me know how your experiments go.  I'm happy to help out if you have questions or if you get stuck, and just got a [Discord server](https://discord.gg/54VGeKk9) running for simple, realtime Q&A.

**Comment by andrewmoise** [comment]
Got it! And sounds good; I am running into the same thing I saw in another issue, where it only is willing to subscribe to people via RSS -- do you want me to investigate it more on my end (under the assumption that me and they are having the same issue)?

I actually was thinking about working myself a little bit on something pretty similar to this (in terms of minimalism / client-centric flexibility for a general Fediverse "reader") under a different architecture, but as you know it takes a pretty significant amount of work. I haven't gotten too far with it. I was pretty psyched to be able to play around with this yeah.

I don't generally use Discord that much; did you think about maybe doing Matrix? I think it's possible that a lot of the Fedi people you will find will gravitate more to Matrix than to Discord.

**Comment by benpate** [comment]
I just had another thought about connecting only via RSS, and [wrote it up in the original issue](https://github.com/EmissarySocial/emissary/issues/358#issuecomment-2068192677).  The gist of it is, if you're running Emissary (or any ActivityPub server) on localhost, you're going to have a hard time making ActivityPub connections.

**Comment by benpate** [comment]
Matrix got really chatty for me, but yeah, I think more fedidevs will be there, instead of Discord.  I'm glad you're checking out Emissary.  Hopefully the architecture is not too weird, and it's worth it to try building on this platform.

When you're comfortable, I'll show you how to define a new "step" in the software.  My goal is to keep the DSL as tight as possible, while still growing over time to accomodate lots of people's use cases.

**Comment by andrewmoise** [comment]
Ah, yeah, makes sense. Right I actually first tried to set the thing up remotely on a globally-accessible server, but I got defeated by #357, so I tried it on my laptop instead. Would you be interested in a PR that adds instructions for how to set up a remote server just by copying the right .conf file, and filling in the right values, instead of using the setup server? Assuming that that's a sensible way to do it? I'll probably set it up that way to further play around with it, at some point.

**Comment by benpate** [comment]
Sure!  I'll take (just about) any PR from (just about) anybody :)

Where would these instructions go?  I could also post them into the emissary.dev website, if there's a place in the QuickStart that makes the most sense.  Let me know what would have helped you the most, and let's put it there.

**Comment by benpate** [comment]
Hey.. I got a Matrix room set up at https://matrix.to/#/#emissary.matrix.org:matrix.org

I'll get it listed on the website here, soon :)

**Comment by andrewmoise** [comment]
Hey, that's awesome! I may come and check it out.

And for the instructions I was thinking of them as going alongside https://emissary.dev/installation (maybe as a linked document from the recommendation to do the setup server). I actually had other recommendations for doc changes there too -- e.g. the links "configuration" and "the Configuration section" near the beginning needs to be changed to point to https://emissary.dev/configuring.

I can just create an issue once I get to that point, with the markdown pasted into the issue, and let you worry about it from there to whatever extent you wanted to apply the changes. If that sounds good?

**Comment by benpate** [comment]
Yeah.  That's probably the best way.  The emissary.dev site is a live Emissary site, not static site generated.  It *is* in markdown, though, so I can just paste it in.

I really appreciate your help here.  I just landed a big change in dev to allow "Follow by Email" that I'm going to try rolling out to production here soon.  The more "other" stuff that people like you are able to do, the better off we all are.  So, thanks!

**Pull request merged**
